steps:
  #build conntainer image
  - name: "gcr.io/cloudbuilders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}:${_TAG}"
      - "."
  #push image to container registry
  - name: "gcr.io/cloudbuilders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
  #deploy image to cloud run
  - name: "gcr.io/google.com/cloudsdktool/cloud_Sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "$SERVICE_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA"
      - "--region"
      - "$_DEPLOY_REGION"
substitutions:
  _REPO_NAME: where-atm-sg
  _TAG: 1.0.4
