services:
  app:
    image: "benjyongzh/where-atm-sg:1.1.0"
    build:
      context: .
    container_name: where-atm-sg
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    command: npm start
