services:
  app:
    image: "benjyongzh/where-atm-sg:1.1.0"
    build:
      context: .
      args:
        - GMAPS_API_KEY=${GMAPS_API_KEY}
        - GMAPS_MAP_ID_LIGHT=${GMAPS_MAP_ID_LIGHT}
    container_name: where-atm-sg
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
    env_file:
      - .env
