services:
  where-atm-sg:
    image: where-atm-sg
    ports:
      - 3000:3000
    secrets:
      - NEXT_PUBLIC_GMAPS_API_KEY
      - NEXT_PUBLIC_GMAPS_MAP_ID_LIGHT
      - GMAPS_API_KEY
secrets:
  NEXT_PUBLIC_GMAPS_API_KEY:
    file: ./.env.local
  NEXT_PUBLIC_GMAPS_MAP_ID_LIGHT:
    file: ./.env.local
  GMAPS_API_KEY:
    file: ./.env.local
