import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";

const fontFamily = Nunito({ subsets: ["latin"] });

import ProviderGroup from "@/components/ProviderGroup";
// import { wrapper } from "@/context/store";

export const metadata: Metadata = {
  title: "Where ATM SG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="cupcake" lang="en">
      <body className={fontFamily.className}>
        <ProviderGroup>{children}</ProviderGroup>
      </body>
    </html>
  );
}
